language: go

install:
  - go get github.com/cheekybits/genny
  - go get code.google.com/p/go-uuid/uuid
  - go get github.com/asp2insp/go-misc/utils
  - go get github.com/asp2insp/go-misc/testutils
  - go get github.com/edsrzf/mmap-go

go:
  - 1.4
  - tip

script: genny -in=runnel.go -out=IntStream.go gen "Typed=int"; go test ./...